name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-format:
    name: Lint Format (Clang-Format)
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run Clang-Format Check
      run: ./caffeine-build/scripts/build.sh linux-native caffeine-app-mvp-format

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run Analysis
      run: ./caffeine-build/scripts/build.sh linux-native caffeine-app-mvp-analyze

#  build-linux:
#    name: Build Linux Native
#    runs-on: ubuntu-24.04
#    steps:
#    - uses: actions/checkout@v4
#      with:
#        submodules: recursive
#
#    - name: Build
#      run: ./caffeine-build/scripts/build.sh linux-native

  build-stm32:
    name: Build STM32 Targets
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        preset: [blinky-board-ex1, blinky-board-ex2]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build ${{ matrix.preset }}
      run: ./caffeine-build/scripts/build.sh ${{ matrix.preset }}
